#!/usr/bin/env python3
"""Shared runtime/config constants for netservices modules."""

import os

TRACE_VERBOSE = os.environ.get("REXGEN_TRACE_VERBOSE", "0") == "1"
CONNECT_FORENSICS = os.environ.get("REXGEN_CONNECT_FORENSICS", "0") == "1"

HEARTBEAT_TIMEOUT_SECONDS = 30
CONNECT_LOCK_TIMEOUT_SECONDS = 90
MAIN_LOOP_INTERVAL_SECONDS = 1
AP_BLOCK_DURATION_SECONDS = 300

NETWORK_SCAN_CACHE_SECONDS_DEFAULT = 10
AP_CLIENTS_CACHE_SECONDS_DEFAULT = 10
RECONNECT_INTERVAL_SECONDS = 60
